spring:
  application:
    name: cta-smokers-api
#  mvc:
#    problemdetails:
#      enabled: true
app:
  version: @project.version@
  aws:
    region: ${AWS_REGION}
    secrets-manager:
      id: ${APP_AWS_SECRETS_MANAGER_ID}
    dynamodb:
      tables:
        smoking-reports: ${APP_AWS_DYNAMODB_TABLES_SMOKING_REPORTS}
  rollbar:
    environment: ${APP_ROLLBAR_ENVIRONMENT}
  cors:
    allowed-origins:
      - https://ctasmokers.com
      - https://www.ctasmokers.com
      - https://cta-smokers-front-end.lagers-rancor-0o.workers.dev
    allowed-methods:
      - GET
      - POST
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Origin-Verify
      - CF-Connecting-IP
  cta:
    reports:
      base-url: ${APP_CTA_REPORTS_BASE_URL}
      page-size: ${APP_AWS_CTA_REPORTS_PAGE_SIZE:25}
      expire-after-minutes: ${APP_AWS_CTA_REPORTS_EXPIRE_AFTER_MINUTES:30}
