spring:
  application:
    name: cta-smokers-api
app:
  aws:
    region: ${AWS_REGION}
    secrets-manager:
      id: ${APP_AWS_SECRETS_MANAGER_ID}
    dynamodb:
      tables:
        smoking-reports: ${APP_AWS_DYNAMODB_TABLES_SMOKING_REPORTS}
  rollbar:
    environment: ${APP_ROLLBAR_ENVIRONMENT}
  cors:
    allowed-origins:
      - https://ctasmokers.com
      - https://www.ctasmokers.com
      - https://cta-smokers-front-end.lagers-rancor-0o.workers.dev
    allowed-methods:
      - GET
      - POST
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Origin-Verify
      - CF-Connecting-IP
  cta:
    reports:
      base-url: ${APP_CTA_REPORTS_BASE_URL}
      page-size: ${APP_AWS_CTA_REPORTS_PAGE_SIZE:25}
      expire-after-minutes: ${APP_AWS_CTA_REPORTS_EXPIRE_AFTER_MINUTES:30}
  openapi:
    info:
      title: CTA Smokers API
      description: API for submitting and retrieving smoking reports on CTA trains.
    contact:
      name: Logan Kulinski
      email: admin@ctasmokers.com
    license:
      name: Apache License 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
    server:
      url: https://api.ctasmokers.com
      description: Production
