spring:
  application:
    name: cta-smokers-api
app:
  aws:
    region: ${AWS_REGION}
    secrets-manager:
      id: ${APP_AWS_SECRETS_MANAGER_ID}
    dynamodb:
      tables:
        smoking-reports: ${APP_AWS_DYNAMODB_TABLES_SMOKING_REPORTS}
  cors:
    allowed-origins:
      - https://ctasmokers.com
      - https://www.ctasmokers.com
      - http://localhost:3000
      - http://localhost:5173
    allowed-methods:
      - GET
      - POST
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Origin-Verify
      - CF-Connecting-IP
  cta:
    reports:
      base-url: ${APP_CTA_REPORTS_BASE_URL}
      page-size: ${APP_AWS_CTA_REPORTS_PAGE_SIZE:25}
      expire-after-hours: ${APP_AWS_CTA_REPORTS_EXPIRE_AFTER_HOURS:12}
