spring:
  application:
    name: cta-smokers-api
app:
  aws:
    region: ${AWS_REGION}
    secrets-manager:
      id: ${APP_AWS_SECRETS_MANAGER_ID}
    dynamodb:
      tables:
        smoking-reports: ${APP_AWS_DYNAMODB_TABLES_SMOKING_REPORTS}
    cta:
      reports:
        page-size: ${APP_AWS_CTA_REPORTS_PAGE_SIZE:25}
        expire-after-hours: ${APP_AWS_CTA_REPORTS_EXPIRE_AFTER_HOURS:12}
